// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// broadcasting_2d_array_multiply
Eigen::VectorXd broadcasting_2d_array_multiply(Eigen::VectorXd x, Eigen::VectorXi dimX, Eigen::VectorXd y, Eigen::VectorXi dimY);
RcppExport SEXP _wombatbasis14_broadcasting_2d_array_multiply(SEXP xSEXP, SEXP dimXSEXP, SEXP ySEXP, SEXP dimYSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type x(xSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXi >::type dimX(dimXSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type y(ySEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXi >::type dimY(dimYSEXP);
    rcpp_result_gen = Rcpp::wrap(broadcasting_2d_array_multiply(x, dimX, y, dimY));
    return rcpp_result_gen;
END_RCPP
}
// broadcasting_3d_array_multiply
Eigen::VectorXd broadcasting_3d_array_multiply(Eigen::VectorXd x, Eigen::VectorXi dimX, Eigen::VectorXd y, Eigen::VectorXi dimY);
RcppExport SEXP _wombatbasis14_broadcasting_3d_array_multiply(SEXP xSEXP, SEXP dimXSEXP, SEXP ySEXP, SEXP dimYSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type x(xSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXi >::type dimX(dimXSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type y(ySEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXi >::type dimY(dimYSEXP);
    rcpp_result_gen = Rcpp::wrap(broadcasting_3d_array_multiply(x, dimX, y, dimY));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_wombatbasis14_broadcasting_2d_array_multiply", (DL_FUNC) &_wombatbasis14_broadcasting_2d_array_multiply, 4},
    {"_wombatbasis14_broadcasting_3d_array_multiply", (DL_FUNC) &_wombatbasis14_broadcasting_3d_array_multiply, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_wombatbasis14(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
