# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

broadcasting_2d_array_multiply <- function(x, dimX, y, dimY) {
    .Call(`_wombatbasis14_broadcasting_2d_array_multiply`, x, dimX, y, dimY)
}

broadcasting_3d_array_multiply <- function(x, dimX, y, dimY) {
    .Call(`_wombatbasis14_broadcasting_3d_array_multiply`, x, dimX, y, dimY)
}

